services:
  mariadb:
    container_name: mariadb
    image: mariadb:inception
    build: requirements/mariadb
    volumes:
      - /home/kseligma/data/mariadb:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "mariadb_healthcheck.sh"]
      start_period: 15s
    env_file:
      - .env
    restart: on-failure
  nginx:
    container_name: nginx
    image: nginx:inception
    build: requirements/nginx
    volumes:
      - /home/kseligma/data/wordpress:/var/www/wordpress
    networks:
      - inception
    ports:
      - 443:443
    depends_on:
      wordpress:
        condition: service_started
      mariadb:
        condition: service_healthy
    restart: on-failure
  wordpress:
    container_name: wordpress
    image: wordpress:inception
    build: requirements/wordpress
    volumes:
      - /home/kseligma/data/wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file:
      - .env
    restart: on-failure
  redis:
    container_name: redis
    image: redis:inception
    build: requirements/bonus/redis
    volumes:
      - /home/kseligma/data/wordpress:/var/www/wordpress
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "redis_healthcheck.sh"]
    env_file:
      - .env
    restart: on-failure
  adminer:
    container_name: adminer
    image: adminer:inception
    build: requirements/bonus/adminer
    networks:
      - inception
    ports:
      - 8080:8080
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    restart: on-failure

networks:
  inception:
    name: inception
