services:
  mariadb:
    container_name: mariadb
    image: mariadb:inception
    build: requirements/mariadb
    volumes:
      - /home/kseligma/data/mariadb:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "mariadb_healthcheck.sh"]
      start_period: 15s
    env_file:
      - .env
    restart: on-failure
  nginx:
    container_name: nginx
    image: nginx:inception
    build: requirements/nginx
    volumes:
      - /home/kseligma/data/wordpress:/var/www/wordpress
      - /home/kseligma/data/html:/var/www/html
    networks:
      - inception
    depends_on:
      wordpress:
        condition: service_started
      adminer:
        condition: service_started
      mailhog:
        condition: service_started
    ports:
      - 443:443
      - 80:80
    restart: on-failure
  wordpress:
    container_name: wordpress
    image: wordpress:inception
    build: requirements/wordpress
    volumes:
      - /home/kseligma/data/wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailhog:
        condition: service_started
    env_file:
      - .env
    restart: on-failure
  redis:
    container_name: redis
    image: redis:inception
    build: requirements/bonus/redis
    volumes:
      - /home/kseligma/data/wordpress:/var/www/wordpress
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "redis_healthcheck.sh"]
    env_file:
      - .env
    restart: on-failure
  adminer:
    container_name: adminer
    image: adminer:inception
    build: requirements/bonus/adminer
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    restart: on-failure
  vsftpd:
    container_name: vsftpd
    image: vsftpd:inception
    build:
      context: requirements/bonus/vsftpd
      args:
        PASSWORD: ${VSFTPD_USER_PASSWORD}
    volumes:
      - /home/kseligma/data/wordpress:/var/www/wordpress
    networks:
      - inception
    ports:
      - 21:21
      - 40000:40000
    env_file:
      - .env
    restart: on-failure
  mailhog:
    container_name: mailhog
    image: mailhog:inception
    build: requirements/bonus/mailhog
    restart: on-failure
    networks:
      - inception
    ports:
      - 1025:1025

networks:
  inception:
    name: inception
